"""Initial migration

Revision ID: 49bb4c3805fd
Revises: 
Create Date: 2025-04-12 22:28:16.749211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bb4c3805fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('pet_friend')
        batch_op.drop_column('cook_freq')
        batch_op.drop_column('smoking_freq')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('guest_freq')
        batch_op.drop_column('bio')
        batch_op.drop_column('noise_tole')
        batch_op.drop_column('communication')
        batch_op.drop_column('clean')
        batch_op.drop_column('sleep_sch')
        batch_op.drop_column('work_hr')
        batch_op.drop_column('financial')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleanliness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sleep_schedule', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('noise_tolerance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guest_frequency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('communication_style', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('financial_habits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pet_friendliness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cooking_frequency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('work_study_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smoking_preferences', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('smoking_preferences')
        batch_op.drop_column('work_study_hours')
        batch_op.drop_column('cooking_frequency')
        batch_op.drop_column('pet_friendliness')
        batch_op.drop_column('financial_habits')
        batch_op.drop_column('communication_style')
        batch_op.drop_column('guest_frequency')
        batch_op.drop_column('noise_tolerance')
        batch_op.drop_column('sleep_schedule')
        batch_op.drop_column('cleanliness')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('work_hr', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sleep_sch', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('clean', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('communication', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('noise_tole', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('guest_freq', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('smoking_freq', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cook_freq', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pet_friend', sa.FLOAT(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
